Repository zonemaster/zonemaster-gui, pull requests merged in 2020-04, with the labels that each got.

#110 Create empty dir for faqs generation
  src/assets/faqs/.gitkeep
Labels: A-BuildSystem

#111 Update dependencies
  angular.json
  package-lock.json
  package.json
  src/polyfills.ts
  yarn.lock
Labels: A-BuildSystem

#112 update tsconfig for ivy engine
  src/tsconfig.app.json
Labels: A-BuildSystem, S-ProposalExists

#85 Updates in prepartion for release v2019.2
  Changes
Labels: P-High

#117 Added space after string
  src/assets/i18n/da.json
Labels: A-Translation, T-Bug

#120 New logotype for Zonemaster (GUI)
  src/assets/images/zonemaster_logo_2020_color.svg
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: A-Documentation

#116 Translated untranslated phrases
  src/assets/i18n/sv.json
Labels: A-Translation

#124 fix(nav): remove github icon when the size is under 1300px to avoid lang issue
  src/app/components/navigation/navigation.component.css
Labels: T-Usability

#127 Merge master into develop (GUI)
  docs/Installation.md
  src/app/components/form/form.component.html
Labels: T-Bug

#128 Updated installation instruction for FreeBSD
  docs/Installation.md
Labels: A-Installation

#129 Adding missing unzip for installation on Ubuntu/Debian
  docs/Installation.md
Labels: A-Installation
