Repository zonemaster/zonemaster-gui, pull requests merged in 2020-11, with the labels that each got.

#152 Fix documentation
  docs/Installation.md
Labels: A-Documentation

#148 Fix fragment in notice box
  docs/FAQ/gui-faq-da.md
  docs/FAQ/gui-faq-fr.md
  e2e/FR16.e2e-spec.ts
  src/app/components/domain/domain.component.html
Labels: A-Code

#156 For release v2020.1 (GUI)
  Changes
  docs/Installation.md
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: P-High

#157 Merge develop into master
  .travis.yml
  Changes
  docs/FAQ/gui-faq-da.md
  docs/FAQ/gui-faq-fr.md
  docs/Installation.md
  e2e/FR16.e2e-spec.ts
  e2e/FR19.e2e-spec.ts
  e2e/FR20.e2e-spec.ts
  e2e/FR21.e2e-spec.ts
  package-lock.json
  package.json
  src/app/components/domain/domain.component.html
  src/app/components/domain/domain.component.ts
  src/app/components/footer/footer.component.ts
  src/app/components/form/form.component.html
  src/app/components/form/form.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/result/result.component.html
  src/app/components/result/result.component.ts
  src/app/services/dns-check.service.ts
  src/assets/i18n/da.json
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/assets/i18n/sv.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: P-High
