Repository zonemaster/zonemaster-gui, pull requests merged in 2020-03, with the labels that each got.

#100 adding numbers of algorithm and digest for convenience
  src/app/components/form/form.component.html
Labels: A-Code, T-Feature

#103 Removed temporary files that should not be in git
  src/assets/faqs/gui-faq-da.html
  src/assets/faqs/gui-faq-en.html
  src/assets/faqs/gui-faq-fr.html
  src/assets/faqs/gui-faq-ru.html
  src/assets/faqs/gui-faq-sv.html
Labels: A-BuildSystem

#101 Update of Swedish FAQ
  docs/FAQ/gui-faq-sv.md
Labels: A-Translation

#102 Updated DNSSEC algorithms in drop-down list
  e2e/FR20.e2e-spec.ts
  src/app/components/form/form.component.html
  src/app/interceptors/mock.interceptor.ts
Labels: A-Code, T-Usability
