Repository zonemaster/zonemaster-gui, pull requests merged in 2021-04, with the labels that each got.

#184 Add Finnish language support in GUI
  docs/FAQ/gui-faq-fi.md
  package.json
  src/app/app.module.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.ts
  src/assets/i18n/fi.json
Labels: A-Translation

#191 Consistent date format
  src/app/components/history/history.component.html
  src/app/components/result/result.component.html
Labels: T-Usability

#192 Tweak to put links just below the navbar
  docs/FAQ/gui-faq-da.md
  docs/FAQ/gui-faq-en.md
  docs/FAQ/gui-faq-fr.md
  docs/FAQ/gui-faq-sv.md
  docs/TranslationGuide.md
  src/app/components/faq/faq.component.css
Labels: A-Code

#185 Added Norwegian translation to web and FAQ pages
  docs/FAQ/gui-faq-nb.md
  src/assets/i18n/nb.json
Labels: A-Translation

#174 Add norwegian (nb)
  package.json
  src/app/app.module.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.ts
Labels: A-Translation

#196 Removes dead code
  src/app/components/domain/domain.component.html
Labels: A-Code

#195 Updated e2e language tests
  docs/TranslationGuide.md
  e2e/FR05-da.e2e-spec.ts
  e2e/FR05-en.e2e-spec.ts
  e2e/FR05-fi.e2e-spec.ts
  e2e/FR05-fr.e2e-spec.ts
  e2e/FR05-nb.e2e-spec.ts
  e2e/FR05-sv.e2e-spec.ts
Labels: A-Travis
