Repository zonemaster/zonemaster-gui, pull requests merged in 2021-06, with the labels that each got.

#206 Merge develop into master (GUI)
  .github/pull_request_template.md
  .gitignore
  Changes
  docs/FAQ/gui-faq-da.md
  docs/FAQ/gui-faq-en.md
  docs/FAQ/gui-faq-fi.md
  docs/FAQ/gui-faq-fr.md
  docs/FAQ/gui-faq-nb.md
  docs/FAQ/gui-faq-sv.md
  docs/Installation.md
  docs/TranslationGuide.md
  e2e/FR05-da.e2e-spec.ts
  e2e/FR05-en.e2e-spec.ts
  e2e/FR05-fi.e2e-spec.ts
  e2e/FR05-fr.e2e-spec.ts
  e2e/FR05-nb.e2e-spec.ts
  e2e/FR05-sv.e2e-spec.ts
  package.json
  src/app/app.module.ts
  src/app/components/domain/domain.component.html
  src/app/components/faq/faq.component.css
  src/app/components/history/history.component.html
  src/app/components/navigation/navigation.component.html
  src/app/components/navigation/navigation.component.ts
  src/app/components/result/result.component.html
  src/assets/i18n/da.json
  src/assets/i18n/en.json
  src/assets/i18n/fi.json
  src/assets/i18n/fr.json
  src/assets/i18n/nb.json
  src/assets/i18n/sv.json
  src/assets/images/zonemaster_logo_2021_color.png
  src/environments/environment.prod.ts
  src/environments/environment.ts
  zonemaster.conf-example
Labels: P-High

#207 Follow Github redirection in Installation instruction
  docs/Installation.md
Labels: A-Documentation, T-Bug

#211 Merge develop into master
  docs/Installation.md
Labels: P-High

#220 pin webdriver version
  .travis.yml
  e2e/FR22.e2e-spec.ts
  e2e/FR24.e2e-spec.ts
Labels: P-High

#227 Fix DS placeholder
  src/app/components/form/form.component.html
  src/app/components/form/form.component.ts
Labels: T-Bug

#214 Updates installation instruction for FreeBSD
  docs/Installation.md
Labels: A-Documentation
