Repository zonemaster/zonemaster-gui, pull requests merged in 2021-01, with the labels that each got.

#162 Resolve issue #161
  e2e/FR10.e2e-spec.ts
  src/app/components/domain/domain.component.html
  src/app/components/form/form.component.html
  src/assets/i18n/da.json
  src/assets/i18n/en.json
  src/assets/i18n/fr.json
  src/assets/i18n/sv.json
Labels: A-Translation

#166 Remove third party stylesheet
  src/index.html
Labels: A-Code

#169 Check if browser language is supported
  src/app/components/navigation/navigation.component.ts
Labels: A-Code, T-Bug

#172 Centos installation
  docs/Installation.md
Labels: A-Installation, P-High
