Repository zonemaster/zonemaster-gui, pull requests merged in 2022-11, with the labels that each got.

#347 Update English FAQ
  docs/FAQ/gui-faq-en.md
Labels: A-Documentation

#337 Use a drop down menu to select between languages
  e2e/FR05.e2e-spec.ts
  e2e/utils/app.utils.ts
  src/app/components/navigation/navigation.component.css
  src/app/components/navigation/navigation.component.html
Labels: V-Minor

#346 Update Zonemaster and DNS descriptive texts
  src/app/components/domain/domain.component.html
  src/locale/messages.da.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fi.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.nb.xlf
  src/locale/messages.sv.xlf
  src/locale/messages.xlf
Labels: A-Documentation

#339 Rewording and provide new URL path `/run-test` instead of `/check` (former `/domain_check`)
  docs/API.md
  e2e/FR02.e2e-spec.ts
  e2e/FR03.e2e-spec.ts
  e2e/FR05.e2e-spec.ts
  e2e/FR08.e2e-spec.ts
  e2e/FR09.e2e-spec.ts
  e2e/FR10.e2e-spec.ts
  e2e/FR15.e2e-spec.ts-snapshots/domain-with-options-chromium-linux.png
  e2e/FR18.e2e-spec.ts
  e2e/FR19.e2e-spec.ts
  e2e/FR20.e2e-spec.ts
  e2e/FR21.e2e-spec.ts
  e2e/FR22.e2e-spec.ts
  e2e/FR26.e2e-spec.ts
  e2e/navigation.e2e-spec.ts
  e2e/redirect.e2e-spec.ts
  src/app/app.module.ts
  src/app/components/domain/domain.component.html
  src/app/components/form/form.component.css
  src/app/components/form/form.component.html
  src/app/components/form/form.component.ts
  src/app/components/navigation/navigation.component.html
  src/app/components/result/result.component.html
  src/app/components/result/result.component.ts
  src/app/components/run-test/run-test.component.css
  src/app/components/run-test/run-test.component.html
  src/app/components/run-test/run-test.component.ts
  src/locale/messages.da.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fi.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.nb.xlf
  src/locale/messages.sv.xlf
  src/locale/messages.xlf
Labels: V-Minor

#365 Force footer to the viewport's bottom
  src/app/app.component.css
  src/app/app.component.html
  src/styles.scss
Labels: V-Minor

#360 Update French version of the FAQ
  docs/FAQ/gui-faq-fr.md
Labels: A-Translation, V-Patch

#341 New ui for test results
  e2e/FR11.e2e-spec.ts-snapshots/domain-chromium-linux.png
  e2e/FR15.e2e-spec.ts-snapshots/domain-with-options-chromium-linux.png
  e2e/FR21.e2e-spec.ts
  e2e/FR21.e2e-spec.ts-snapshots/results-chromium-linux.png
  e2e/FR22.e2e-spec.ts
  src/app/app.module.ts
  src/app/components/footer/footer.component.css
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.ts
  src/app/components/result/result.component.css
  src/app/components/result/result.component.html
  src/app/components/result/result.component.ts
  src/app/interceptors/mock.interceptor.ts
  src/app/pipes/filter-by-categories.pipe.ts
  src/app/pipes/filter.pipe.ts
  src/styles.scss
Labels: V-Major

#368 Add license to distribution archive
  scripts/create_release.js
Labels: P-High, V-Patch

#367 Update the license wording to unify with the other repositories
  README.md
Labels: A-Documentation, V-Patch

#364 Domain test form update
  e2e/FR10.e2e-spec.ts
  e2e/FR11.e2e-spec.ts-snapshots/domain-chromium-linux.png
  e2e/FR13.e2e-spec.ts
  e2e/FR15.e2e-spec.ts-snapshots/domain-with-options-chromium-linux.png
  e2e/FR21.e2e-spec.ts-snapshots/results-chromium-linux.png
  e2e/utils/app.utils.ts
  playwright.config.ts
  src/app/components/domain/domain.component.html
  src/app/components/form/form.component.css
  src/app/components/form/form.component.html
  src/app/components/form/form.component.ts
  src/app/components/header/header.component.css
  src/app/components/result/result.component.css
  src/app/components/result/result.component.html
  src/app/components/run-test/run-test.component.html
  src/app/components/run-test/run-test.component.ts
  src/app/interceptors/mock.interceptor.ts
  src/styles.scss
Labels: V-Minor

#369 Fix notifications behaviour
  src/app/components/alert/alert.component.css
  src/app/components/alert/alert.component.html
  src/app/components/alert/alert.component.ts
  src/app/components/result/result.component.ts
  src/app/components/run-test/run-test.component.ts
Labels: T-Bug
