Repository zonemaster/zonemaster-gui, pull requests merged in 2022-08, with the labels that each got.

#335 GUI API document
  docs/API.md
Labels: A-Documentation

#334 Perform a test through the URL directly
  e2e/FR02.e2e-spec.ts
  e2e/FR09.e2e-spec.ts
  e2e/navigation.e2e-spec.ts
  e2e/redirect.e2e-spec.ts
  src/app/app.module.ts
  src/app/components/form/form.component.ts
  src/app/components/navigation/navigation.component.html
Labels: T-Feature

#332 fix logo customization key name in documentation
  docs/Configuration.md
  src/assets/app.config.sample.json
Labels: A-Documentation, T-Bug

#331 Fix FAQ links when serving from custom base
  scripts/faq.js
Labels: T-Bug
