Repository zonemaster/zonemaster-gui, pull requests merged in 2022-12, with the labels that each got.

#370 Update translation
  docs/TranslationGuide.md
  package.json
  src/app/components/footer/footer.component.ts
  src/app/components/form/form.component.html
  src/app/components/history/history.component.html
  src/app/components/result/result.component.html
  src/app/components/result/result.component.ts
  src/app/components/run-test/run-test.component.ts
  src/locale/messages.da.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fi.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.nb.xlf
  src/locale/messages.sv.xlf
  src/locale/messages.xlf
Labels: A-Translation, V-Patch

#375 Deduplicate the assets directory
  docs/Installation.md
  scripts/create_release.js
  zonemaster.conf-example
Labels: T-Bug

#376 Redirect deprecated path
  zonemaster.conf-example
Labels: V-Patch

#363 Patch 1
  docs/FAQ/gui-faq-da.md
Labels: A-Translation, V-Patch

#361 Translation update 2022 11 11
  docs/FAQ/gui-faq-nb.md
Labels: A-Translation, V-Patch

#359 Spanish FAQ Translation update
  docs/FAQ/gui-faq-es.md
Labels: A-Translation, V-Patch

#379 Prepare release v2022.2 (GUI)
  Changes
  docs/Installation.md
  package.json
  src/environments/version.ts
Labels: P-High
