Repository zonemaster/zonemaster-gui, pull requests merged in 2023-05, with the labels that each got.

#401 Improve accessibility of the result page
  e2e/FR22.e2e-spec.ts
  src/app/components/result/result.component.css
  src/app/components/result/result.component.html
  src/app/components/result/result.component.ts
Labels: V-Patch

#405 Translate used ngb components
  package.json
  src/locale/messages.da.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fi.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.nb.xlf
  src/locale/messages.sv.xlf
  src/locale/messages.xlf
Labels: A-Translation, V-Patch

#403 Improve footer
  src/app/components/footer/footer.component.css
  src/app/components/footer/footer.component.html
  src/app/interceptors/mock.interceptor.ts
Labels: V-Patch

#400 Remove randomization of attributes in Angular
  src/app/app.component.css
  src/app/app.component.ts
  src/app/components/alert/alert.component.css
  src/app/components/alert/alert.component.ts
  src/app/components/domain/domain.component.css
  src/app/components/domain/domain.component.ts
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.ts
  src/app/components/footer/footer.component.ts
  src/app/components/form/form.component.css
  src/app/components/form/form.component.ts
  src/app/components/header/header.component.ts
  src/app/components/history/history.component.ts
  src/app/components/navigation/navigation.component.css
  src/app/components/navigation/navigation.component.ts
  src/app/components/page-not-found/page-not-found.component.ts
  src/app/components/result/result.component.css
  src/app/components/result/result.component.ts
  src/app/components/run-test/run-test.component.ts
Labels: V-Patch

#414 add missing strings to translation files
  src/app/components/footer/footer.component.html
  src/locale/messages.da.xlf
  src/locale/messages.es.xlf
  src/locale/messages.fi.xlf
  src/locale/messages.fr.xlf
  src/locale/messages.nb.xlf
  src/locale/messages.sv.xlf
  src/locale/messages.xlf
Labels: A-Translation, V-Patch

#411 remove github logo
  e2e/FR11.e2e-spec.ts-snapshots/domain-chromium-linux.png
  src/app/components/navigation/navigation.component.css
  src/app/components/navigation/navigation.component.html
Labels: V-Minor

#415 fix build status badge
  README.md
Labels: A-Documentation, V-Patch

#408 Make room for optional footer logo
  docs/Configuration.md
  src/app/components/footer/footer.component.css
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.ts
  src/assets/app.config.sample.json
  src/environments/common.ts
Labels: V-Patch

#407 Moves HTML anchor into header and creates valid HTML
  docs/FAQ/gui-faq-da.md
  docs/FAQ/gui-faq-en.md
  docs/FAQ/gui-faq-es.md
  docs/FAQ/gui-faq-fi.md
  docs/FAQ/gui-faq-fr.md
  docs/FAQ/gui-faq-nb.md
  docs/FAQ/gui-faq-sv.md
  docs/TranslationGuide.md
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.ts
Labels: V-Patch

#416 Small improvement of the run test page
  e2e/FR11.e2e-spec.ts-snapshots/domain-chromium-linux.png
  e2e/FR15.e2e-spec.ts-snapshots/domain-with-options-chromium-linux.png
  e2e/FR21.e2e-spec.ts-snapshots/results-chromium-linux.png
  playwright.config.ts
  src/app/components/form/form.component.css
  src/app/components/form/form.component.html
  src/app/components/run-test/run-test.component.css
  src/app/components/run-test/run-test.component.html
Labels: V-Minor

#417 use github action instead of travis
  .github/workflows/ci.yml
  .travis.yml
Labels: V-Patch

#420 Updates the translation of GUI strings into Finnish
  src/locale/messages.fi.xlf
Labels: A-Translation, V-Patch

#422 Updates GUI strings to Swedish
  src/locale/messages.sv.xlf
Labels: A-Translation, V-Patch

#424 Remove documentation (moved to zonemaster/zonemaster)
  README.md
  docs/API.md
  docs/Configuration.md
  docs/Installation.md
  docs/Testing.md
  docs/TranslationGuide.md
Labels: A-Documentation, V-Patch
